import { describe, it, expect } from "vitest";
import {
    signAccessToken,
    verifyAccessToken,
    generateRefreshToken,
    hashRefreshToken,
    generateSecureToken,
    parseDuration,
} from "../lib/jwt.js";

describe("jwt", () => {
    describe("signAccessToken / verifyAccessToken", () => {
        it("should sign and verify a valid token", () => {
            const token = signAccessToken({
                userId: "user-123",
                role: "USER",
                emailVerified: true,
            });

            expect(typeof token).toBe("string");
            expect(token.split(".")).toHaveLength(3);

            const decoded = verifyAccessToken(token);
            expect(decoded.sub).toBe("user-123");
            expect(decoded.role).toBe("USER");
            expect(decoded.emailVerified).toBe(true);
            expect(decoded.iat).toBeDefined();
            expect(decoded.exp).toBeDefined();
        });

        it("should reject a tampered token", () => {
            const token = signAccessToken({
                userId: "user-123",
                role: "USER",
                emailVerified: true,
            });

            const tampered = token.slice(0, -5) + "XXXXX";
            expect(() => verifyAccessToken(tampered)).toThrow();
        });

        it("should reject a completely invalid string", () => {
            expect(() => verifyAccessToken("not.a.jwt")).toThrow();
        });
    });

    describe("generateRefreshToken", () => {
        it("should return raw and hash properties", () => {
            const { raw, hash } = generateRefreshToken();

            expect(typeof raw).toBe("string");
            expect(raw.length).toBeGreaterThan(20);
            expect(hash).toMatch(/^[0-9a-f]{64}$/);
        });

        it("should generate unique tokens each call", () => {
            const a = generateRefreshToken();
            const b = generateRefreshToken();
            expect(a.raw).not.toBe(b.raw);
            expect(a.hash).not.toBe(b.hash);
        });
    });

    describe("hashRefreshToken", () => {
        it("should match hash generated by generateRefreshToken", () => {
            const { raw, hash } = generateRefreshToken();
            expect(hashRefreshToken(raw)).toBe(hash);
        });

        it("should be deterministic", () => {
            expect(hashRefreshToken("test-token")).toBe(hashRefreshToken("test-token"));
        });
    });

    describe("generateSecureToken", () => {
        it("should return raw and hash properties", () => {
            const { raw, hash } = generateSecureToken();
            expect(typeof raw).toBe("string");
            expect(hash).toMatch(/^[0-9a-f]{64}$/);
        });
    });

    describe("parseDuration", () => {
        it("should parse seconds", () => {
            expect(parseDuration("30s")).toBe(30_000);
        });

        it("should parse minutes", () => {
            expect(parseDuration("15m")).toBe(900_000);
        });

        it("should parse hours", () => {
            expect(parseDuration("2h")).toBe(7_200_000);
        });

        it("should parse days", () => {
            expect(parseDuration("30d")).toBe(2_592_000_000);
        });

        it("should throw on invalid format", () => {
            expect(() => parseDuration("abc")).toThrow("Invalid duration format");
            expect(() => parseDuration("15x")).toThrow("Invalid duration format");
            expect(() => parseDuration("")).toThrow("Invalid duration format");
        });
    });
});
